### ISSUE TITLE
Benchmark not ablet to run

### ISSUE THREAD

**Issue by delaneyj** [zandaqo/structurae#11]
Tried with both `yarn && yarn benchmark` and `npm i && npm run benchmark` getting the same output on node v12.3.0 on a Ubuntu 19.10 box.  

```
> structurae@1.8.0 benchmark /home/delaney/work/black/structurae
> node bench/index.js
/home/delaney/work/structurae/bench/bits.js:20
class Person extends BitField {}
                     ^

TypeError: Class extends value #<Object> is not a constructor or null
    at Object.<anonymous> (/home/delaney/work/structurae/bench/bits.js:20:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/delaney/work/structurae/bench/index.js:2:6)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by zandaqo** [comment]
A benchmark imported directly from a class file instead of the main entry point, and it broke when the export signature of the file changed. It's fixed now in the master. Thanks for reporting this!
